# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, unique=True, verbose_name='Article Title')),
                ('date_posted', models.DateTimeField(verbose_name='Posted on date')),
                ('read_time', models.CharField(default=None, max_length=10, unique=True, verbose_name='Article read time')),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Article Featured Image')),
                ('content', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=models.CharField(default=None, max_length=100, unique=True, verbose_name='Article Title'), unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, unique=True, verbose_name='Course Title')),
                ('date_posted', models.DateTimeField(verbose_name='Posted on date')),
                ('read_time', models.CharField(default=None, max_length=10, unique=True, verbose_name='Course duration')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='', verbose_name='Course Featured Image')),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=models.CharField(default=None, max_length=100, unique=True, verbose_name='Course Title'), unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simillar', models.ManyToManyField(blank=True, null=True, related_name='_courses_simillar_+', to='LearningCentre.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, unique=True, verbose_name='Video Title')),
                ('date_posted', models.DateTimeField(verbose_name='Posted on date')),
                ('play_time', models.CharField(default=None, max_length=10, unique=True, verbose_name='Video play time')),
                ('content', models.TextField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Article Featured Image')),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=models.CharField(default=None, max_length=100, unique=True, verbose_name='Video Title'), unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='videos',
            field=models.ManyToManyField(related_name='video', to='LearningCentre.Videos'),
        ),
    ]
