# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': "Article's"},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='read_time',
            field=models.TextField(default=None, max_length=10, unique=True, verbose_name='Course duration'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
