# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0002_auto_20170117_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'Articles'},
        ),
    ]
