# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:20
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0008_auto_20170117_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
