# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0010_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='read_time',
            field=models.CharField(default=None, max_length=10, verbose_name='Article read time'),
        ),
    ]
