# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0012_auto_20170118_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='short_description',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
