# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0013_auto_20170118_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
