# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0015_auto_20170119_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='p', max_length=1, verbose_name='Article status'),
        ),
    ]
