# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0020_auto_20170120_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='alt_tag',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Add an image alt tage'),
        ),
        migrations.AddField(
            model_name='courses',
            name='alt_tag',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Add an image alt tage'),
        ),
        migrations.AddField(
            model_name='videos',
            name='alt_tag',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Add an image alt tage'),
        ),
    ]
