# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 20:48
from __future__ import unicode_literals

import Tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('icon', models.FileField(null=True, upload_to=Tools.models.upload_location)),
                ('slug', models.SlugField(default=models.CharField(max_length=40), unique=True)),
                ('featured', models.NullBooleanField()),
                ('plan', models.ManyToManyField(related_name='tools', to='pricing.Plan')),
            ],
        ),
    ]
