# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Tool Featured Image'),
        ),
        migrations.AddField(
            model_name='tool',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additioanl Notes for Tooltip'),
        ),
    ]
