# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0003_tool_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Additioanl Notes for Tooltip'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=400, null=True, verbose_name='Short description(max length 400 charachters)'),
        ),
    ]
