# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0004_auto_20170118_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
