# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 09:57
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0005_auto_20170118_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=150, null=True, verbose_name='Short description(max length 150 charachters)'),
        ),
    ]
