# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='structured_data',
            field=models.TextField(blank=True, null=True, verbose_name='Structured Data'),
        ),
    ]
