# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 18:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_page_structured_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='structured_data',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Structured Data'),
        ),
    ]
