# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20170119_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Google Analytics code')),
                ('facebook_handle', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Facebook handle')),
                ('twitter_handle', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Facebook handle')),
            ],
        ),
    ]
