# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='twitter_handle',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Twiiter handle'),
        ),
    ]
