# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_auto_20170120_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
